const data ={
    products:[
        {
            _id:'1',
            name:'Nike slim tops',
            category:'tops',
            images:'l',
            price:120,
            countInStock:10,
            brand:'nike',
            rating:2.5,
            numReviews:10,
            description:'nice brand',
        },
        {
            _id:'2',
            name:'Nike slim tops',
            category:'tops',
            images:'m',
            price:120,
            countInStock:10,
            brand:'nike',
            rating:4.5,
            numReviews:10,
            description:'nice brand',
        },
        {
            _id:'3',
            name:'Nike slim tops',
            category:'tops',
            images:'n',
            price:120,
            countInStock:0,
            brand:'nike',
            rating:4.5,
            numReviews:10,
            description:'nice brand',
        },
    ],
};
export default data;